---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ctse-workout-client"
  namespace: "default"
  labels:
    app: "ctse-workout-client"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "ctse-workout-client"
  template:
    metadata:
      labels:
        app: "ctse-workout-client"
    spec:
      containers:
      - name: "ctseworkout-1"
        image: "gcr.io/animated-backup-349310/github.com/yasoja44/ctseworkout:$SHORT_SHA"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ctse-workout-client-hpa-2g3n"
  namespace: "default"
  labels:
    app: "ctse-workout-client"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ctse-workout-client"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
